### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by weiweikong** [vooon/rarog#1]
Hi, I am interesting about the fixed-wing simulation with Gazebo and MAVROS. Also, I would like to fly my fixed-wing in real sense with PX4. So I need some simulation to test my vision-based algorithms. From your Youtube website, it seems works fine. Could you share more infromation about this?

I tried to `catkin_make` this package, but it require the `ntpd_driver`. I googled it, but stll confused about it  with this fixed-wing model.

**Comment by vooon** [comment]
For now that package not for simulation, for deploy on real onboard computer.

But it allow to replay rosbag's (youtube video).
Needed deps here: https://github.com/vooon/rarog/blob/master/rarog_configs/rarog.rosinstall
(but now also need mavlink version 2015.10.10).

**Comment by weiweikong** [comment]
Ok, I will test it. Are you using Pixhawk hardware with PX4 ? or APM.
By the way, any suggestion about the fixed-wing simulation with MAVROS and PX4 POSIX ? I would like to do some research related to onboard computer vision and path planning, so it would be better to test all algorithms SITL or HIL.

**Comment by vooon** [comment]
Pixhawk with PX4 firmware.
I think you could setup SITL with X-Plane & QGC and then connect mavros.

**Comment by weiweikong** [comment]
But in my experience,  X-Plane could not support the simulation of single/stereo camera and laser, yet Gazebo-based simulation can easily achieve it. So the fixed-wing model with Gazebo is required. What is your seggestion?

**Comment by vooon** [comment]
You may try [«last letter»](http://georacer.github.io/last_letter/index.html), but it wants ROS Indigo, Ubuntu 14.04 and for now APM SITL.
